// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the TestModule module
	public static void aCT_HashString(IContext context, testmodule.proxies.PageHelper _pageHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PageHelper", _pageHelper == null ? null : _pageHelper.getMendixObject());
		Core.microflowCall("TestModule.ACT_HashString").withParams(params).execute(context);
	}
	public static boolean aSU_AfterStartUp(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("TestModule.ASU_AfterStartUp").withParams(params).execute(context);
	}
	public static testmodule.proxies.PageHelper dSS_GetPageHelper(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TestModule.DSS_GetPageHelper").withParams(params).execute(context);
		return result == null ? null : testmodule.proxies.PageHelper.initialize(context, result);
	}
}
