// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package stringtomd5hash.actions;

import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Base64;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class StringToSignature extends CustomJavaAction<java.lang.String>
{
	private java.lang.String string;

	public StringToSignature(IContext context, java.lang.String string)
	{
		super(context);
		this.string = string;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Charset charset = StandardCharsets.UTF_8;
		MessageDigest md = MessageDigest.getInstance("MD5");
		    byte[] byteArray = string.getBytes(charset);;
			md.update(byteArray);
		byte[] md5hash = md.digest();
		return Base64.getEncoder().encodeToString(md5hash);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringToSignature";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
